### PR TITLE
Bugfix/consensus

### LINKED ISSUE #594: [BUG] Failed to setValue ... "Invalid object for states: /"
Error logs (see the attached log file for details):
```
2021-09-29T08:29:29.847Z [node-0-8080] error: [CONSENSUS] Previous block's epoch (20361616) is greater than or equal to incoming block's (20361616)
2021-09-29T08:29:35.057Z [node-0-8080] error: [FUNCTIONS]   ==> Failed to setValue on '/staking/consensus/0x004A2550661c8a306207C9dabb279d5701fFD66e/0/expire_at' with error: {"error_message":"Invalid object for states: /","code":101,"bandwidth_gas_amount":1}
2021-09-29T08:29:35.058Z [node-0-8080] error: [CONSENSUS] Failed to execute the proposal tx: {"gas_amount_total":{"bandwidth":{"service":3},"state":{"service":0}},"gas_cost_total":0,"result_list":{"0":{"error_message":"Triggered function call failed","func_results":{"_handleOffenses":{"op_results":{"0":{"path":"/consensus/offense_records/0x004A2550661c8a306207C9dabb279d5701fFD66e","result":{"code":0,"bandwidth_gas_amount":1}},"1":{"path":"/staking/consensus/0x004A2550661c8a306207C9dabb279d5701fFD66e/0/expire_at","result":{"error_message":"Invalid object for states: /","code":101,"bandwidth_gas_amount":1}}},"code":0,"bandwidth_gas_amount":0},"_distributeFee":{"code":0,"bandwidth_gas_amount":0}},"code":105,"bandwidth_gas_amount":1}}}
2021-09-29T08:29:35.720Z [node-0-8080] error: [FUNCTIONS]   ==> Failed to setValue on '/staking/consensus/0x004A2550661c8a306207C9dabb279d5701fFD66e/0/expire_at' with error: {"error_message":"Invalid object for states: /","code":101,"bandwidth_gas_amount":1}
...
```

Screen Shot 2021-09-29 at 7 13 37 PM

[node-0-8080-error-2021-09-29.log](https://github.com/ainblockchain/ain-blockchain/files/7250975/node-0-8080-error-2021-09-29.log)

### LINKED ISSUE #595: [BUG] Broken consensus integration tests
Test run logs:
```
$ yarn run test_integration_consensus
yarn run v1.22.10
$ ./node_modules/mocha/bin/mocha --timeout 640000 integration/consensus.test.js


  Consensus
Iteration count exceeded its limit before the network is ready (["http://localhost:8085"])
    Validators
Iteration count exceeded its limit before the given tx 0x9e555ecd3789ea90c25689762c90c7d8b2e03fb9ca6c6751a07c24522e433289 is finalized!
Failed to check finalization of server5's staking tx.
Iteration count exceeded its limit before server5 becomes a validator
      1) Number of validators cannot exceed MAX_NUM_VALIDATORS
      2) When more than MAX_NUM_VALIDATORS validators exist, validatators with bigger stakes get prioritized
    Rewards
Iteration count exceeded its limit before the given tx 0xf922905fc609e99bb6ebe42e729f4886ea1dca42f3ba1469ca4e026600a73b0d is finalized!
Failed to check finalization of tx.
      ✓ consensus rewards are updated (103626ms)
Iteration count exceeded its limit before the given tx 0x502868756a37be8e0017f7054bba34cb680ee048bcee9243b787df3df05d0f5f is finalized!
Failed to check finalization of tx.
      ✓ cannot claim more than unclaimed rewards (102604ms)
Iteration count exceeded its limit before the given tx 0xdc937ea779d02ee22c71ae8ee76f49a780a424fdb09e47ef65c7a67966bf7c9c is finalized!
Failed to check finalization of tx.
      ✓ can claim unclaimed rewards (102346ms)
    Penalties
      ✓ can record an offense and its evidence (11303ms)
      ✓ can penalize malicious validators  (9079ms)


  5 passing (12m)
  2 failing

  1) Consensus
       Validators
         Number of validators cannot exceed MAX_NUM_VALIDATORS:
     AssertionError: server5 is not included in validators
      at Context.<anonymous> (integration/consensus.test.js:229:18)

  2) Consensus
       Validators
         When more than MAX_NUM_VALIDATORS validators exist, validatators with bigger stakes get prioritized:

      AssertionError: expected 100000 to deeply equal 100010
      + expected - actual

      -100000
      +100010
      
      at Context.<anonymous> (integration/consensus.test.js:274:14)



error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by liayoo**
- Fixed #594 
  - Fixed missing blockTime param for executeMultiSetOperation()
  - Updated proposal tx to always be a SET operation (as opposed to SET_VALUE)
- Fixed #595, #591
  - Added temporary env vars to set TARGET_NUM_OUTBOUND_CONNECTION and MAX_NUM_INBOUND_CONNECTION higher than MAX_NUM_VALIDATORS - 1 in consensus integration test
  - Updated to use is_final=true option for get apis for more stable results

### CODE REVIEW

File: db/functions.js [hunk 1]
```diff
@@ -702,7 +702,7 @@ class Functions {
       const lockupExtension = Functions.getLockupExtensionForNewOffenses(numNewOffenses, updatedNumOffenses);
       if (lockupExtension > 0) {
         const expirationPath = PathUtil.getStakingExpirationPath(PredefinedDbPaths.CONSENSUS, offender, 0);
-        const currentExpiration = Math.max(Number(this.db.getValue(expirationPath)), context.blockTime);
+        const currentExpiration = Math.max(Number(this.db.getValue(expirationPath)), context.blockTime || 0);
```
Comment (minsulee2) [inline db/functions.js:705]: is there any case that context.blockTime is undefined or something?

File: consensus/consensus-util.js [hunk 2]
```diff
@@ -68,14 +63,8 @@ class ConsensusUtil {
...
     const op = _get(tx, 'tx_body.operation');
-    if (!tx || !op) return {};
-    if (op.type === WriteDbOperations.SET_VALUE) {
-      return _get(op, 'value.offenses');
-    } else if (op.type === WriteDbOperations.SET) {
-      return _get(op, 'op_list.0.value.offenses');
-    } else {
-      return {};
-    }
+    if (!tx || !op || op.type !== WriteDbOperations.SET) return {};
```
Comment (platfowner) [inline consensus/consensus-util.js:66]: minor: isProposalTx() can be reused?

File: consensus/index.js [hunk 3]
```diff
@@ -370,26 +370,22 @@ class Consensus {
...
-            value: null
-          }
-        ]
-      };
-      return this.node.createTransaction({ operation: setOp, nonce: -1, gas_price: 1 });
+    const setOp = {
+      type: WriteDbOperations.SET,
+      op_list: [proposeOp]
+    };
+    if (blockNumber > ConsensusConsts.MAX_CONSENSUS_STATE_DB) {
```
Comment (platfowner) [inline consensus/index.js:377]: minor: what about 'logs' or something in the name e.g. MAX_CONSENSUS_LOGS, MAX_CONSENSUS_LOGS_IN_STATES?

File: db/functions.js (hunk 1 above)
Comment (platfowner) [reply db/functions.js:705]: +1
doesn't setValue() set its value all the time?

Comment (platfowner) [reply db/functions.js:705]: If there is such a case, it could be safer to apply such a default value at higher level e.g. setValue()?

File: db/functions.js [hunk 4]
```diff
@@ -716,7 +716,7 @@ class Functions {
     const expirationPath = PathUtil.getStakingExpirationPath(serviceName, user, stakingKey);
     const currentExpiration = Number(this.db.getValue(expirationPath));
     const lockup = Number(this.db.getValue(PathUtil.getStakingLockupDurationPath(serviceName)));
-    const newExpiration = context.blockTime + lockup;
+    const newExpiration = (context.blockTime || 0) + lockup;
```
Comment (platfowner) [inline db/functions.js:719]: ditto

File: db/functions.js (hunk 1 above)
Comment (liayoo) [reply db/functions.js]: Right, blockTime should not be undefined or null at this point. This was introduced while testing & removed. Thanks!

File: consensus/consensus-util.js (hunk 2 above)
Comment (liayoo) [reply consensus/consensus-util.js]: Nice! Done!

File: consensus/index.js (hunk 3 above)
Comment (liayoo) [reply consensus/index.js]: Changed to MAX_CONSENSUS_LOGS_IN_STATES. Thanks for the idea!

File: db/functions.js (hunk 4 above)
Comment (liayoo) [reply db/functions.js]: ditto

**Comment by liayoo** [comment]
Addressed all comments, PTAL @minsulee2 @platfowner

**Review by platfowner — APPROVED** [review]
LGTM
Thanks for fixing them quickly!

**Comment by liayoo** [comment]
Thanks all for the fast review! Feels good to see all tests passing 😄 Now merging~
