### PR TITLE
Change keystore file directories to deploy depending on the season.

### LINKED ISSUE #602: [BUG] testnet_dev_staging_keys: No such file or directory
Would it be nicer if the deploy target is controlled depending on the SEASON param?

Error logs:
```
...
testnet_dev_staging_keys: No such file or directory
keystore_node_5.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_9.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_8.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_4.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_3.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_2.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_1.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_0.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_7.json                                                                                                                      100%  491     2.7KB/s   00:00    
keystore_node_6.json                                                                                                                      100%  491     2.7KB/s   00:00    
traffic-stats-manager.js                                                                                                                  100% 1436     8.0KB/s   00:00    
event-counter.js                                                                                                                          100% 1929    10.7KB/s   00:00    
transaction.js                                                                                                                            100% 7675    42.5KB/s   00:00    
index.js                                                                                                                                  100%   17KB  95.4KB/s   00:00    
package.json                                                                                                                              100% 5617    31.1KB/s   00:00    
setup_blockchain_ubuntu.sh                                                                                                                100%  526     2.9KB/s   00:00    
start_node_genesis_gcp.sh                                                                                                                 100% 6214    34.4KB/s   00:00    
start_node_incremental_gcp.sh                                                                                                             100% 7061    39.3KB/s   00:00    
restart_node_gcp.sh                                                                                                                       100% 5941    33.1KB/s   00:00    
wait_until_node_sync_gcp.sh                                                                                                               100%  906     5.0KB/s   00:00    
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
```

### PR DESCRIPTION
**Pull request by liayoo**
- Use different deploy target files (keystore file directory names) for different seasons
- Fixes #602

### CODE REVIEW

File: deploy_blockchain_genesis_gcp.sh [hunk 1]
```diff
@@ -89,7 +89,15 @@ function inject_account() {
 }
 
 FILES_FOR_TRACKER="blockchain/ client/ common/ consensus/ db/ genesis-configs/ logger/ tracker-server/ traffic/ package.json setup_blockchain_ubuntu.sh start_tracker_genesis_gcp.sh start_tracker_incremental_gcp.sh restart_tracker_gcp.sh"
-FILES_FOR_NODE="blockchain/ client/ common/ consensus/ db/ genesis-configs/ json_rpc/ logger/ node/ p2p/ testnet_dev_staging_keys/ testnet_prod_keys/ traffic/ tx-pool/ package.json setup_blockchain_ubuntu.sh start_node_genesis_gcp.sh start_node_incremental_gcp.sh restart_node_gcp.sh wait_until_node_sync_gcp.sh"
+FILES_FOR_NODE="blockchain/ client/ common/ consensus/ db/ genesis-configs/ json_rpc/ logger/ node/ p2p/ traffic/ tx-pool/ package.json setup_blockchain_ubuntu.sh start_node_genesis_gcp.sh start_node_incremental_gcp.sh restart_node_gcp.sh wait_until_node_sync_gcp.sh"
```
Comment (platfowner) [inline deploy_blockchain_genesis_gcp.sh:92]: minor: maybe this could be another option for readability?
```
if [[ "$KEYSTORE_OPTION" != "" ]]; then
    if [[ "$SEASON" = "spring" ]] || [[ "$SEASON" = "summer" ]]; then
        KEYSTORE_DIR="testnet_prod_keys/"
    else
        KEYSTORE_DIR="testnet_dev_staging_keys/"
    fi
fi

FILES_FOR_NODE="blockchain/ client/ ... $KEYSTORE_DIR"
```

Comment (liayoo) [reply deploy_blockchain_genesis_gcp.sh]: Done, thanks for the suggestion!
