### PR TITLE
Bugfix/liayoo/invalid state proof hash

### LINKED ISSUE #649: [BUG] Invalid state proof hash
Error log:
```
2021-10-26T09:24:57.758Z [node-0-8081] error: [NODE] [executeBlockOnDb] Invalid state proof hash (58): 0x9346dbd4dce2979a47c6e8ec2246de136016cffa9fd57adbf0f89b6d0af66c3f, 0x733fa7f672adcb6d6d7954e70ff4d1440a35bff173c5a5a893ab2dc131916e16
```

How to reproduce:
```
sh start_servers_afan_local.sh

kill 62747

MIN_NUM_VALIDATORS=3 ACCOUNT_INDEX=0 CONSOLE_LOG=true ENABLE_DEV_SET_CLIENT_API=true ENABLE_TX_SIG_VERIF_WORKAROUND=true ENABLE_GAS_FEE_WORKAROUND=true BLOCKCHAIN_DATA_DIR=~/ain_blockchain_data node ./client/index.js
```

### PR DESCRIPTION
**Pull request by liayoo**
- Fixed #649 by always setting `restoreIfFails = true` when executing transactions 
- Changed to skip billing & balance pre-checks if `skipFees = true`

### CODE REVIEW

File: db/index.js [hunk 1]
```diff
@@ -1304,6 +1304,9 @@ class DB {
     if (checkNonceTimestampResult !== true) {
       return checkNonceTimestampResult;
     }
+    if (skipFees) {
```
Comment (platfowner) [inline db/index.js:1307]: minor: what about 
```
if (!skipFees) {
  const checkBillingResult = ...
  ...
  const checkBalanceResult = ...
  ...
}

return true;
```
?

**Comment by platfowner** [comment]
Could you leave more about context to https://github.com/ainblockchain/ain-blockchain/issues/649 ?

**Review by platfowner — APPROVED** [review]
LGTM
Thanks for handling it!

File: db/index.js (hunk 1 above)
Comment (liayoo) [reply db/index.js]: Done, thanks!

**Comment by liayoo** [comment]
> Happy to see this fix! Could you leave more about context to #649 ?

Sure! The 'restoreIfFails' arg for executeTransaction() and executeTransactionList() has been set to false for certain cases (loading blocks, merging chain segments) back when we didn't include failed transactions to blocks. It should've been updated to always be true for transactions (but not last_votes) since we now include failed txs, but it wasn't, so when there were failed txs, a restarted node failed to successfully load blocks.
